import Head from "next/head";
import React from "react";
import ThreeDDesign from "@/components/Portfolio/ThreeDDesign";

export default function ThreeDDesignPage() {
  return (
    <div>
      <Head>
        <title>3D Design</title>
        <meta name="description" content="Generated by create next app"></meta>
        <link rel="icon" href="/" />
      </Head>
      <ThreeDDesign />
    </div>
  );
}
