import Head from "next/head";
import React from "react";
import AugmentedReality from "@/components/Portfolio/AugmentedReality";

export default function ARPage() {
  return (
    <div>
      <Head>
        <title>AR</title>
        <meta name="description" content="Generated by create next app"></meta>
        <link rel="icon" href="/" />
      </Head>
      <AugmentedReality />
    </div>
  );
}
