import Head from "next/head";
import React from "react";
import SoftwareDevelopment from "@/components/Portfolio/SoftwareDevelopment";

export default function SoftwareDevelopmentPage() {
  return (
    <div>
      <Head>
        <title>Software Development</title>
        <meta name="description" content="Generated by create next app"></meta>
        <link rel="icon" href="/" />
      </Head>
      <SoftwareDevelopment />
    </div>
  );
}
